### ISSUE TITLE
Spyse API Key (Update)

### ISSUE THREAD

**Issue by Greg-spec** [d34dfr4m3/prettycool#10]
We noticed that you used the API of one of Spyse's products most likely it was Findsubdomains, Cert DB or DNS table. We want to notify you about the release of a new and improved API key which you can find in your personal account at spyse.com. 
Unfortunately, we should stop supporting the old API a few weeks earlier, starting from Monday. Thanks for being with us.

**Comment by d34dfr4m3** [comment]
Thanks, I already update the code to v2 schema. 

But there's another problem, I notice that the Spyse api endpoint (api.spyse.com) is using CloudFlare which blocks clients without javascript. This new component in your infraestructure kill the communication between the clients.

**Comment by Greg-spec** [comment]
We already updated API to v3 and tuned the CloudFlare, it should work fine. But we will test it tomorrow.
Regards

Greg from Spyse
