### ISSUE TITLE
 Spyse API Key (Update)

### ISSUE THREAD

**Issue by Greg-spec** [d34dfr4m3/prettycool#12]
Hi there. You previously used one of our services as a part of your development. We want to notify you, that we are releasing our updated Spyse API search. We hope you will be interested in testing and implementing a much broader functionality to your developments. Thanks for being with us.

**Comment by d34dfr4m3** [comment]
Thanks, I already update the code to v2 schema. 

But there's another problem, I notice that the Spyse api endpoint (api.spyse.com) is using CloudFlare which blocks clients without javascript. This new component in your infraestructure kill the communication between the clients.
